### ISSUE TITLE
Sweep: Add a qr extension to https://github.com/BananaBake/Scratch-3.0-extension-gallery.git

### ISSUE THREAD

**Issue by BananaBake** [BananaBake/Scratch-3.0-extension-gallery#3]
Sweep: Add the extension you create into the extensions folder and list it in the website/index.ejs
https://github.com/BananaBake/Scratch-3.0-extension-gallery/blob/0849d8471a167028a571a4f3f2b022d20f2f0287/website/index.html
it should have the following blocks:
'qr for [text]'

<details>
<summary>Checklist</summary>

- [ ] `extensions/SweepBot/QRCodeGenerator.js`
> • Add the 'use strict'; statement at the top of the file.
> • Create a new class 'QRCodeGenerator' with a method 'getInfo()'. This method should return an object with the id 'sweepbotqrcode', name 'QR Code Generator', and colors for the block.
> • In the 'getInfo()' method, add a blocks array with a single object. This object should have the opcode 'qrForText', blockType as Scratch.BlockType.REPORTER, and text as 'qr for [text]'. The arguments object should have a single property 'text' of type Scratch.ArgumentType.STRING.
> • Implement the 'qrForText(args)' method in the 'QRCodeGenerator' class. This method should take the 'text' argument and generate a QR code for it.
> • At the end of the file, register the new extension using 'Scratch.extensions.register(new QRCodeGenerator());'.

- [ ] `website/index.ejs`
> • Find the section where the extensions are listed.
> • Add a new entry for the 'QR Code Generator' extension. The entry should include the name of the extension, a brief description, and a link to the extension file 'extensions/SweepBot/QRCodeGenerator.js'.

</details>

**Comment by wwzeng1** [comment]
Hi @BananaBake! noticed you had an error here. Can I help you with Sweep? Would love to do this over a call

**Comment by wwzeng1** [comment]
Our email is team@sweep.dev if you're available :)

**Comment by BananaBake** [comment]
sweep: why do I always have to give you the permanent for you to work?
I should just be able to say the index.ejs without having to give you the permanent!

**Comment by wwzeng1** [comment]
Hey @BananaBake did you mean to reference https://github.com/BananaBake/Scratch-3.0-extension-gallery/blob/master/website/index.html?

**Comment by BananaBake** [comment]
sweep; here why did I have to add the link when you should've been able to find it in my repo?
(I know because of one of the other ones, you said you couldn't find the file and it only ended up working when I gave you the link)
#9
